language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- npm test
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: EbwDetgsAAG+0w1+IintYVa383BpDKOQKYkeo9jXgFS6cjGUFLG52dZuuPyywqG9RlPnVd4S4+P/Uzn+KEYpV/ufVUzs3qxdqiBZRQl70FR/ubnLEdWiNQCwLET5YJ+kzzbOshyydNP01jp+0zeuhdX/C0HLCGns3cqV41v3162cySmfw9T72AbAzOr5SWTcIUnVc0Xtn+PguvqLnFqzcgaaVlpiE6aWmJnPPh8NdsvdPAv5a1FbQXBB00qpumL9xzizB4tGcDJwUEMu7wdtA7LlyJShM5DvEyK1Xm9T2XC2DN8EhfIJiGdUXZtIsT6/mlR8h0Wtp9i+nECMuAvbuqZKtKUgk/yq3llLIMFVHedyvn9pmx4pxD1pJp8AxN/lj9czpLxsHAXZAkarJGbgQukZYQCMIzZjDfor9cXxWTgAmJl/1f0Ezfz4RlZvnv6/IZFfFG8yFHY8jA2oOJKREi30CDRC6dlqIwm+Dfzg2Hy+bAGPcioK1aiaCtdSBoQoytsqUTrcbus4icRY3wklMWg6WmmCcrBdXOHy1P25gw7xDyUsLbXJJu6QhsrwSjZQku+9ExOW2FeBBiKGru9TbKPzwqvIxcCefzFpptX94w9Vp0c5XWsjdVJc5klB2OQ7AVkP6/wMtuLKdLrmJX4s5/uTHH02R/3HT+iVwf/L74E=
  app:
    master: im-www
