ember:
  image: danlynn/ember-cli:1.13.8
  ports:
   - "80:4200"
   - "49152:49152"
  volumes:
   - .:/tmp/myapp
  entrypoint:
   - sh
  command: -c "tar -xmf /tmp/myapp/tmp/init.tar && npm install && bower install --allow-root && ember server"
