ember:
  image: danlynn/ember-cli:1.13.8
  ports:
   - "80:4200"
   - "35729:35729"
  volumes:
   - .:/tmp/myapp
  entrypoint:
   - sh
  command: -c "tar -xmf /tmp/myapp/tmp/init.tar && ember server"
